baseurl = "/"
languageCode = "en-us"
title = "Eben Mallory portfolio"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-104998295-1"
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Eben Mallory"
	description = "Promotional portfolio website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "portrait.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Hello! and welcome to my portfolio"
		# The icons will be shown if you enter your username
		twitter = ""
		github = "ebenryanmallory"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "https://www.linkedin.com/in/eben-mallory-17250017/"

		copyright = [
			"Made with ♥ in Colorado"
		]


	[params.about]
		hide  = false
		title = "Front end and animation design portfolio"
		content = "Side projects, personality and interest pieces, and all around weirdness"


	[params.portfolio]
		hide  = false
		title = "Select Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/cat.jpg"
			thumb = "thumbs/cat-thumb.jpg"
			title = "Iams Ad School student project"
			description = "Healthy diet = healthy fur."

		[[params.portfolio.gallery]]
			image = "fulls/1.jpg"
			thumb = "thumbs/mcdonalds-thumb.jpg"
			title = "McDonald's Ad School project"
			description = "International D&AD student award winner"

		[[params.portfolio.gallery]]
			image = "fulls/nami-bottle.jpg"
			thumb = "thumbs/nami-bottle-thumb.jpg"
			title = "Nami in a bottle"
			description = "3D render inspired by (and stolen from) the popular video game League of Legends."

		[[params.portfolio.gallery]]
			image = "fulls/bard.jpg"
			thumb = "thumbs/bard-thumbnail.jpg"
			title = "Bard"
			description = "3D render of the character Bard from League of Legends."

	[params.recentposts]
		hide  = false
		title = "Latest rants on code and frameworks"

	[params.contact]
		hide  = false
		title = "REACH OUT"
		content = "Business inquiries are more than welcome"

		address = [
			"931 N 19th St",
			"Colorado Springs, CO 80904"
		]
		phone = "(970) 300-1125"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "ebenryanmallory@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "About"
	url  = "about"
	weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
    
[[menu.main]]
	name = "Hire Me"
	url  = "/hire-me/"
	weight = 15
